name: Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # could install requirements.txt here
    - name: Run unit tests
      run: |
        pattern="(.*)_test\.py"
        directory="./botiverse-tests"
        for root in $(find $directory -type d); do
          for file in $(find $root -maxdepth 1 -type f); do
            if [[ $file =~ $pattern ]]; then
              echo "$file"
              python -m unittest discover "$root" -p "${file##*/}"
            fi
          done
        done